FROM alpine:latest AS builder
RUN apk add build-base
COPY src/lat_ctx_docker/docker_proc.c docker_proc.c
RUN gcc -o docker_proc docker_proc.c

FROM alpine:latest
RUN mkdir /pipes
WORKDIR /bin
COPY --from=builder docker_proc .
ENTRYPOINT ["docker_proc"]