FROM archlinux:latest AS builder
RUN pacman -Syu --noconfirm
RUN pacman -S gcc --noconfirm
COPY src/lat_ctx_docker/docker_proc.c docker_proc.c
RUN gcc -o docker_proc docker_proc.c

FROM archlinux:latest
RUN mkdir /pipes
WORKDIR /bin
COPY --from=builder docker_proc .
ENTRYPOINT ["docker_proc"]